### ISSUE TITLE
move notebook bits into their own folder

### ISSUE THREAD

**Issue by grahamgower** [RacimoLab/simGL#7]
I'm not really sure how to deal with the notebook stuff. Partly because I don't personally use notebooks (and thus don't know about best practices), but partly because they don't integrate well with source control. Any time one (re)runs a notebook, the file changes and introduces a bunch of irrelevant differences between the checked out file and the commited file.

Maybe it could be converted into jupyter-book documentation?

**Comment by MoiColl** [comment]
I'm now used to code in Jupyternotebooks because I can integrate both code and text in a logical way to explain my train of thought. Besides, I perform tests that for me are much easier to follow and understand than just uploading regular code with comments or even no explanation. If is not too much of a problem, I'd rather keep it even if it is in a different folder.
